### ISSUE TITLE
Momit has closed

### ISSUE THREAD

**Issue by SapientPizza** [Photonios/py-momit-cool-remote#2]
It seems you're right momit has gone out of business.

Can we redirect send commands to their devices somehow now that their cloud is dead?

**Comment by Photonios** [comment]
Hello,

Sorry it took so long to get back to this. It indeed seems Momit has gone out of business. I also got the e-mail. I

It's winter where I live so I have little use for my AC at the moment and the need to toy with my AC is at a low point at the moment.

As it says in the README, this package will continue working, even without the Momit servers online. I do not know how the Momit Cool itself works with their servers down. All I know is that this package does not depend on their servers in any way. It might be possible to emulate their servers, but I am not sure how.

I'll get back to this at some point and see if I can figure something out as I'd like to continue using this :)
